services:
  saleor-storefront:
    container_name: saleor-storefront
    build:
      context: ..
      dockerfile: storefront/Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL:-http://api.localhost:10000/graphql/}
        NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL:-http://storefront.localhost:10000}
    restart: unless-stopped
    networks:
      - digidex-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storefront.rule=Host(`storefront.localhost`)"
      - "traefik.http.routers.storefront.entrypoints=web"
      - "traefik.http.services.storefront.loadbalancer.server.port=3000"

networks:
  digidex-net:
    external: true
